apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: {{ include "spring-service.fullname" . }}
spec:
  prefix: /api/spring-service/
  service: {{ .Chart.Name }}
  resolver: {{ .Values.resolver }}
  load_balancer:
    policy: round_robin