apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: polygot-microservices
build:
  artifacts:
    - image: subhakarkotta/polygot-microservices-python
      context: applications/python-service
      docker:
         dockerfile: Dockerfile
    - image: subhakarkotta/polygot-microservices-spring
      context: applications/spring-service
      jib: {}
    - image: subhakarkotta/polygot-microservices-go
      context: applications/go-service
      docker:
         dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: go-service 
        wait: true
        chartPath: helm-charts/go-service
        namespace: default
        artifactOverrides:
          image.repository: subhakarkotta/polygot-microservices-go
        valuesFiles: [ helm-charts/go-service/values.yaml ]
      - name: python-service 
        wait: true
        chartPath: helm-charts/python-service
        namespace: default
        artifactOverrides:
          image.repository: subhakarkotta/polygot-microservices-python
        setValues:
          resolver: consul-dc1
        valuesFiles: [ helm-charts/python-service/values.yaml ]
      - name: spring-service 
        wait: true
        chartPath: helm-charts/spring-service
        namespace: default
        artifactOverrides:
          image.repository: subhakarkotta/polygot-microservices-spring
        setValues:
          resolver: consul-dc1
        valuesFiles: [ helm-charts/spring-service/values.yaml ]