apiVersion: getambassador.io/v2
kind: ConsulResolver
metadata:
  name: {{ .Values.resolver.name }}
  namespace: ambassador
spec:
  address: "{{ .Values.consul.host }}:{{ .Values.consul.port }}"
  datacenter: microservices-dc-1