apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: {{ include "python-service.fullname" . }}
spec:
  prefix: /api/python-service/
  service: {{ .Chart.Name }}
  resolver: {{ .Values.resolver }}
  load_balancer:
    policy: round_robin